package com.bbva.hancock.sdk;

import com.bbva.hancock.sdk.config.HancockConfig;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigBeanFactory;
import com.typesafe.config.ConfigFactory;
import org.web3j.crypto.Credentials;
import org.web3j.crypto.RawTransaction;
import org.web3j.crypto.TransactionEncoder;
import org.web3j.crypto.WalletUtils;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.Web3jFactory;
import org.web3j.protocol.core.methods.response.EthSendTransaction;
import org.web3j.protocol.http.HttpService;
import org.web3j.utils.Numeric;

import java.io.File;
import java.math.BigInteger;
import java.util.concurrent.ExecutionException;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class HancockEthereumClient {

    private HancockConfig config;

    public HancockEthereumClient() {

        this.config = this.loadPrivateConfig();

    }

    public HancockEthereumClient(HancockConfig config) throws Exception {

        this.config = this.loadPrivateConfig();
        BeanUtils.merge(this.config, config);

    }

    public EthereumWallet generateWallet() throws Exception {

        try {

            String pass = "__123456__";

            File tmpDirectory = new File("/tmp/wallets");
            tmpDirectory.mkdirs();

            String fileName = WalletUtils.generateNewWalletFile(pass, tmpDirectory, false);
            Credentials credentials = WalletUtils.loadCredentials(pass, tmpDirectory + "/" + fileName);

            tmpDirectory.delete();

            String address = credentials.getAddress();
            String privateKey = "0x" + credentials.getEcKeyPair().getPrivateKey().toString(16);
            String publicKey = "0x" + credentials.getEcKeyPair().getPublicKey().toString(16);

            return new EthereumWallet(address, privateKey, publicKey);

        } catch (Exception error) {

            System.out.println("error: " + error.toString());
            throw new Exception("Error generating wallet");

        }

    }

    public RawTransaction createRawTransaction(BigInteger nonce, BigInteger gasPrice, BigInteger gasLimit, String to,
                                       BigInteger value) {
        return RawTransaction.createEtherTransaction(nonce, gasPrice, gasLimit, to, value);
    }

    public String signTransaction(RawTransaction rawTransaction, String privateKey) {

        Credentials credentials = Credentials.create(privateKey);
        byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
        String hexValue = Numeric.toHexString(signedMessage);

        return hexValue;
    }

    public String sendSignedTransaction(String signedTransaction, boolean locally) throws Exception {

        if (locally) {

            return this.sendSignedTransactionLocally(signedTransaction);

        } else {

            return this.sendSignedTransactionRemotely(signedTransaction);

        }

    }

    private String sendSignedTransactionLocally(String signedTransaction) throws InterruptedException, ExecutionException {

        // defaults to http://localhost:8545/
        String nodeUrl = this.config.getNode().getHost() + ':' + this.config.getNode().getPort();
        Web3j web3j = Web3jFactory.build(new HttpService(nodeUrl));

        EthSendTransaction ethSendTransaction = web3j.ethSendRawTransaction(signedTransaction).sendAsync().get();
        String transactionHash = ethSendTransaction.getTransactionHash();
        // poll for transaction response via org.web3j.protocol.Web3j.ethGetTransactionReceipt(<txHash>)

        return transactionHash;

    }

    private String sendSignedTransactionRemotely(String signedTransaction) throws Exception {

       throw new Exception("Not implemented");

    }

    private HancockConfig loadPrivateConfig() {
        Config baseConfig = ConfigFactory.load();
        Config config, specificConfig;

        try {

            specificConfig = ConfigFactory.load(System.getenv("BUILD_ENV"));
            config = baseConfig.withFallback(specificConfig);

        } catch (Exception e) {

            config = baseConfig;

        }

        HancockConfig hancockConfig = ConfigBeanFactory.create(config, HancockConfig.class);
        return hancockConfig;
    }


}