env: "local"
adapter:
  host: http://localhost
  port: 3000
  base: ''
  resources:
    balance: '/ethereum/balance/__ADDRESS__'
    transfer: '/ethereum/transfers'
    tokenTransfer: '/ethereum/token/__ADDRESS_OR_ALIAS__/transfer'
    tokenTransferFrom: '/ethereum/token/__ADDRESS_OR_ALIAS__/transferFrom'
    tokenBalance: '/ethereum/token/__ADDRESS_OR_ALIAS__/balance/__ADDRESS__'
    tokenMetadata: '/ethereum/token/__ADDRESS_OR_ALIAS__/metadata'
    tokenAllowance: '/ethereum/token/__ADDRESS_OR_ALIAS__/allowance'
    tokenApprove: '/ethereum/token/__ADDRESS_OR_ALIAS__/approve'
    tokenRegister: '/ethereum/token/register'
    decode: '/protocol/decode'
    encode: '/protocol/encode'
node:
  host: http://localhost
  port: 8545
