env: "local"
adapter:
  host: http://localhost
  port: 3000
  base: ''
  resources:
    balance: '/ethereum/balance/__ADDRESS__'
    transfer: '/ethereum/transfers'
node:
  host: http://localhost
  port: 8545
