env: "local"
adapter:
  host: http://localhost
  port: 3000
  base: ''
  resources:
    balance: '/ethereum/balance/__ADDRESS__'
    transfer: '/ethereum/transfers'
    tokenTransfer: '/ethereum/token/__ADDRESS_OR_ALIAS__/transfers'
    decode: '/protocol/decode'
    encode: '/protocol/encode'
node:
  host: http://localhost
  port: 8545
