package com.bbva.hancock.sdk.dlt.ethereum.clients;

import com.bbva.hancock.sdk.HancockClient;
import com.bbva.hancock.sdk.config.HancockConfig;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class HancockEthereumClient extends HancockClient {

    private HancockEthereumProtocolClient protocolClient;
    private HancockEthereumWalletClient walletClient;
    private HancockEthereumTransferClient transferClient;
    private HancockEthereumTokenClient tokenClient;
    private HancockEthereumSmartContractClient smartContractClient;
    private HancockEthereumTransactionClient transactionClient;

    public HancockEthereumClient(HancockConfig config) throws Exception {

        super(config);
        this.protocolClient = new HancockEthereumProtocolClient(config);
        this.walletClient = new HancockEthereumWalletClient(config);
        this.transactionClient = new HancockEthereumTransactionClient(config);
        this.transferClient = new HancockEthereumTransferClient(config, this.transactionClient);
        this.tokenClient = new HancockEthereumTokenClient(config, this.transactionClient);
        this.smartContractClient = new HancockEthereumSmartContractClient(config, this.transactionClient);
    }

    public HancockEthereumProtocolClient getProtocolClient() {
        return protocolClient;
    }

    public HancockEthereumWalletClient getWalletClient() {
        return walletClient;
    }

    public HancockEthereumTransferClient getTransferClient() {
        return transferClient;
    }

    public HancockEthereumTokenClient getTokenClient() {
        return tokenClient;
    }

    public HancockEthereumSmartContractClient getSmartContractClient() {
        return smartContractClient;
    }

    public HancockEthereumTransactionClient getTransactionClient() {
        return transactionClient;
    }

    // TODO: Support yaml load config on android
    /*private HancockConfig loadPrivateConfig() {
        Config baseConfig = ConfigFactory.load();
        Config config, specificConfig;

        try {

            specificConfig = ConfigFactory.load(System.getenv("BUILD_ENV"));
            config = baseConfig.withFallback(specificConfig);

        } catch (Exception e) {

            config = baseConfig;

        }

        HancockConfig hancockConfig = ConfigBeanFactory.create(config, HancockConfig.class);
        return hancockConfig;
    }*/


}